version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: bookstore_db
    environment:
      MYSQL_ROOT_PASSWORD: MyPassword!@1814
      MYSQL_DATABASE: BOOK_STORE
      MYSQL_USER: root
      MYSQL_PASSWORD: MyPassword!@1814
    ports:
      - "3307:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data: