spring:
  application:
    name: bookstore

  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: Atoof000000
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none    # Use Flyway for schema management
    show-sql: true
    properties:
      hibernate:
        format_sql: true

flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true   # Avoids errors if DB has existing tables
    baseline-version: 0

server:
  port: 8080

stripe:
  apiUrl: https://api.stripe.com
  enabled: true

AppConfig:
  Stripe: true
  host: http://localhost:8080

jpa:
  show-sql: true